<?php

namespace App\Services\Club;

use App\Models\Club;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * ClubService - Handles club-related business logic
 * 
 * This service is responsible for:
 * - Creating, updating, and managing clubs
 * - Club status management (active, inactive)
 * - Club approval workflow
 */
class ClubService
{
    /**
     * Create a new club.
     * 
     * @param array $data Club data
     * @param User $creator The user creating the club
     * @return Club
     */
    public function create(array $data, User $creator): Club
    {
        return DB::transaction(function () use ($data, $creator) {
            // Set required fields
            $data['created_by'] = $creator->id;
            
            // Admin-created clubs are immediately active and approved
            $data['status'] = 'active';
            $data['approved_at'] = now();
            $data['approved_by'] = $creator->id;

            // Create the club (slug will be auto-generated by model boot method)
            return Club::create($data);
        });
    }

    /**
     * Approve a pending club.
     * 
     * @param Club $club The club to approve
     * @param User $approver The user approving the club
     * @param bool $activate Whether to set status to 'active' immediately
     * @return Club
     * @throws \Exception If club is already approved
     */
    public function approve(Club $club, User $approver, bool $activate = true): Club
    {
        if ($club->approved_at !== null) {
            throw new \Exception("Club is already approved.");
        }

        return DB::transaction(function () use ($club, $approver, $activate) {
            $club->approved_at = now();
            $club->approved_by = $approver->id;

            if ($activate) {
                $club->status = 'active';
            }

            $club->save();

            return $club->fresh();
        });
    }

    /**
     * Reject a pending club.
     * 
     * @param Club $club The club to reject
     * @param User $rejector The user rejecting the club
     * @param string|null $reason Optional rejection reason
     * @return Club
     */
    public function reject(Club $club, User $rejector, ?string $reason = null): Club
    {
        return DB::transaction(function () use ($club, $rejector, $reason) {
            $club->status = 'rejected';
            
            if ($reason !== null && Schema::hasColumn('clubs', 'rejection_reason')) {
                $club->rejection_reason = $reason;
            }

            $club->save();

            return $club->fresh();
        });
    }

    /**
     * Activate a club.
     * 
     * @param Club $club The club to activate
     * @return Club
     * @throws \Exception If club cannot be activated
     */
    public function activate(Club $club): Club
    {
        if ($club->status === 'active') {
            throw new \Exception("Club is already active.");
        }

        return DB::transaction(function () use ($club) {
            $club->status = 'active';
            $club->save();

            return $club->fresh();
        });
    }

    /**
     * Deactivate a club.
     * 
     * @param Club $club The club to deactivate
     * @param string|null $reason Optional reason for deactivation
     * @return Club
     * @throws \Exception If club cannot be deactivated
     */
    public function deactivate(Club $club, ?string $reason = null): Club
    {
        if ($club->status === 'inactive') {
            throw new \Exception("Club is already inactive.");
        }

        if ($club->status !== 'active') {
            throw new \Exception("Only active clubs can be deactivated.");
        }

        return DB::transaction(function () use ($club, $reason) {
            $club->status = 'inactive';

            if ($reason !== null && Schema::hasColumn('clubs', 'deactivation_reason')) {
                $club->deactivation_reason = $reason;
            }

            $club->save();

            return $club->fresh();
        });
    }

    /**
     * Update a club.
     * 
     * @param Club $club The club to update
     * @param array $data Data to update
     * @return Club
     */
    public function update(Club $club, array $data): Club
    {
        $club->update($data);
        return $club->fresh();
    }

    /**
     * Get club for a club account user.
     * 
     * @param User $clubAccount The club account user
     * @return Club|null
     */
    public function getClubForAccount(User $clubAccount): ?Club
    {
        return Club::where('club_user_id', $clubAccount->id)->first();
    }

    /**
     * Get clubs pending approval.
     * 
     * @param array $filters Optional filters
     * @return Collection|Club[]
     */
    public function getPendingClubs(array $filters = []): Collection
    {
        $query = Club::whereNull('approved_at');

        if (isset($filters['created_after'])) {
            $query->where('created_at', '>=', $filters['created_after']);
        }

        if (isset($filters['created_by'])) {
            $query->where('created_by', $filters['created_by']);
        }

        return $query->get();
    }

    /**
     * Get active clubs with statistics.
     * 
     * @param array $filters Optional filters
     * @return Collection|Club[]
     */
    public function getActiveClubsWithStats(array $filters = []): Collection
    {
        $query = Club::where('status', 'active')
            ->withCount('members');

        if (isset($filters['search'])) {
            $query->where(function ($q) use ($filters) {
                $q->where('name', 'like', "%{$filters['search']}%")
                  ->orWhere('description', 'like', "%{$filters['search']}%");
            });
        }

        return $query->get();
    }

    /**
     * Check if a club is active.
     * 
     * @param Club $club The club
     * @return bool
     */
    public function isActive(Club $club): bool
    {
        return $club->status === 'active';
    }

    /**
     * Check if a club slug is available.
     * 
     * @param string $slug The slug to check
     * @param Club|null $excludeClub Club to exclude from uniqueness check
     * @return bool
     */
    public function isSlugAvailable(string $slug, ?Club $excludeClub = null): bool
    {
        $query = Club::where('slug', $slug);

        if ($excludeClub) {
            $query->where('id', '!=', $excludeClub->id);
        }

        return !$query->exists();
    }
}


