<?php

namespace App\Services;

use App\Models\Club;
use App\Models\ClubJoinRequest;
use App\Models\ClubLog;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ClubFacade
{
    /**
     * Create a new club.
     * 
     * Admin-created clubs are immediately active and approved.
     * Handles slug generation, sets creator, and initializes approval status.
     * 
     * @param array $data Club data (name, description, email, phone, logo, etc.)
     * @param User $creator The user creating the club
     * @return Club
     * @throws \Exception If creation fails or creator is not an admin
     */
    public function createClub(array $data, User $creator): Club
    {
        // Enforce role-based access control: only admins can create clubs
        if ($creator->role !== 'admin') {
            throw new \Exception("Only administrators are allowed to create clubs.");
        }

        return DB::transaction(function () use ($data, $creator) {
            // Set required fields
            $data['created_by'] = $creator->id;
            
            // Admin-created clubs are immediately active and approved
            $data['status'] = 'active';
            $data['approved_at'] = now();
            $data['approved_by'] = $creator->id;

            // Create the club (slug will be auto-generated by model boot method)
            $club = Club::create($data);

            $this->log($club, 'create_club', $creator);

            return $club->fresh();
        });
    }

    /**
     * Approve a pending club.
     * 
     * Sets approved_at timestamp, approved_by user, and optionally activates the club.
     * 
     * @param Club $club The club to approve
     * @param User $approver The user approving the club
     * @param bool $activate Whether to set status to 'active' immediately
     * @return Club
     * @throws \Exception If approval fails or club is already approved
     */
    public function approveClub(Club $club, User $approver, bool $activate = true): Club
    {
        // Check if club is already approved
        if ($club->approved_at !== null) {
            throw new \Exception("Club is already approved.");
        }

        return DB::transaction(function () use ($club, $approver, $activate) {
            // Set approval fields
            $club->approved_at = now();
            $club->approved_by = $approver->id;

            // Set status to 'active' if activate is true, otherwise keep current status
            if ($activate) {
                $club->status = 'active';
            }

            $club->save();

            $this->log($club, 'approve_club', $approver);

            return $club->fresh();
        });
    }

    /**
     * Reject a pending club.
     * 
     * Optionally sets rejection reason and updates status.
     * 
     * @param Club $club The club to reject
     * @param User $rejector The user rejecting the club
     * @param string|null $reason Optional rejection reason
     * @return Club
     */
    public function rejectClub(Club $club, User $rejector, ?string $reason = null): Club
    {
        //
    }

    /**
     * Add a member to a club with specified role.
     * 
     * Handles duplicate membership checks and role assignment.
     * 
     * @param Club $club The club to add member to
     * @param User $user The user to add as member
     * @param string|null $role Optional role (e.g., 'member', 'officer', 'treasurer')
     * @return bool True if member was added, false if already a member
     * @throws \Exception If user cannot be added
     */
    public function addMember(Club $club, User $user, ?string $role = null): bool
    {
        // Validate that user is a student (not admin or club account)
        if (!in_array($user->role, ['user', 'student'])) {
            throw new \Exception("Only students can be added as club members.");
        }

        // Check if user is already a member
        if ($club->members()->where('users.id', $user->id)->exists()) {
            return false;
        }

        // Add user with specified role or default to 'member'
        $club->members()->attach($user->id, [
            'role' => $role ?? 'member',
        ]);

        $this->log($club, 'add_member', auth()->user() ?? $club->creator, $user);

        return true;
    }

    /**
     * Remove a member from a club.
     * 
     * Handles cleanup of member-related data and prevents removal of club admin.
     * 
     * @param Club $club The club to remove member from
     * @param User $user The user to remove
     * @param User|null $removedBy The user performing the removal (for audit)
     * @return bool True if member was removed
     * @throws \Exception If removal is not allowed
     */
    public function removeMember(Club $club, User $user, ?User $removedBy = null): bool
    {
        // Check if user is a member of the club
        if (!$club->members()->where('users.id', $user->id)->exists()) {
            throw new \Exception("User is not a member of this club.");
        }

        // Validate that user is a student (not admin or club account)
        if (!in_array($user->role, ['user', 'student'])) {
            throw new \Exception("Only student members can be removed from clubs.");
        }

        // Remove user from the pivot table
        $club->members()->detach($user->id);

        $actor = $removedBy ?? auth()->user() ?? $club->creator;
        $this->log($club, 'remove_member', $actor, $user);

        return true;
    }

    /**
     * Get club for a club account user.
     * 
     * Finds the club associated with a club account user via club_user_id.
     * 
     * @param User $clubAccount The club account user
     * @return Club|null The club associated with the account, or null if not found
     */
    public function getClubForAccount(User $clubAccount): ?Club
    {
        return Club::where('club_user_id', $clubAccount->id)->first();
    }

    /**
     * List all members of a club.
     * 
     * Returns all student members from the club_user pivot table.
     * 
     * @param Club $club The club
     * @return Collection|User[] Collection of member users
     */
    public function listMembers(Club $club): Collection
    {
        return $club->members()->get();
    }

    /**
     * Check if a club is active.
     * 
     * @param Club $club The club
     * @return bool True if club status is 'active'
     */
    public function isActive(Club $club): bool
    {
        return $club->status === 'active';
    }

    /**
     * Check if a user is a member of a club.
     * 
     * @param Club $club The club
     * @param User $user The user to check
     * @return bool True if user is a member
     */
    public function hasMember(Club $club, User $user): bool
    {
        return $club->members()->where('users.id', $user->id)->exists();
    }

    /**
     * Get the role of a member in a club.
     * 
     * @param Club $club The club
     * @param User $user The member user
     * @return string|null The member's role, or null if not a member
     */
    public function getMemberRole(Club $club, User $user): ?string
    {
        $member = $club->members()->where('users.id', $user->id)->first();
        
        return $member?->pivot->role ?? null;
    }

    /**
     * Count the number of members in a club.
     * 
     * @param Club $club The club
     * @return int Number of members
     */
    public function countMembers(Club $club): int
    {
        return $club->members()->count();
    }

    /**
     * Update a member's role in a club.
     * 
     * Validates role changes and prevents unauthorized role modifications.
     * 
     * @param Club $club The club
     * @param User $user The member whose role to update
     * @param string $newRole The new role to assign
     * @param User|null $updatedBy The user making the change (for audit)
     * @return bool True if role was updated
     * @throws \Exception If role update is not allowed
     */
    public function updateMemberRole(Club $club, User $user, string $newRole, ?User $updatedBy = null): bool
    {
        // Check if user is a member of the club
        if (!$club->members()->where('users.id', $user->id)->exists()) {
            throw new \Exception("User is not a member of this club.");
        }

        // Update the role in the pivot table
        $club->members()->updateExistingPivot($user->id, [
            'role' => $newRole,
        ]);

        return true;
    }

    /**
     * Activate a club.
     * 
     * Sets status to 'active' and performs necessary validations.
     * 
     * @param Club $club The club to activate
     * @param User|null $activatedBy The user activating the club
     * @return Club
     * @throws \Exception If club cannot be activated
     */
    public function activateClub(Club $club, ?User $activatedBy = null): Club
    {
        //
    }

    /**
     * Deactivate a club.
     * 
     * Sets status to 'inactive' and handles related cleanup (e.g., cancel future events).
     * 
     * @param Club $club The club to deactivate
     * @param User|null $deactivatedBy The user deactivating the club
     * @param string|null $reason Optional reason for deactivation
     * @return Club
     */
    public function deactivateClub(Club $club, ?User $deactivatedBy = null, ?string $reason = null): Club
    {
        // Check if club is already inactive
        if ($club->status === 'inactive') {
            throw new \Exception("Club is already inactive.");
        }

        // Check if club is active (must be active to be deactivated)
        if ($club->status !== 'active') {
            throw new \Exception("Only active clubs can be deactivated.");
        }

        return DB::transaction(function () use ($club, $reason, $deactivatedBy) {
            // Set status to inactive
            $club->status = 'inactive';

            // Store reason if provided and column exists
            if ($reason !== null && Schema::hasColumn('clubs', 'deactivation_reason')) {
                $club->deactivation_reason = $reason;
            }

            $club->save();

            if ($deactivatedBy) {
                $this->log($club, 'deactivate_club', $deactivatedBy);
            }

            return $club->fresh();
        });
    }

    /**
     * Transfer club ownership/administration to another user.
     * 
     * Updates created_by, handles role transfers, and validates permissions.
     * 
     * @param Club $club The club to transfer
     * @param User $newOwner The new owner/administrator
     * @param User $transferredBy The user performing the transfer
     * @return Club
     * @throws \Exception If transfer is not allowed
     */
    public function transferOwnership(Club $club, User $newOwner, User $transferredBy): Club
    {
        //
    }

    /**
     * Check if a user can perform an action on a club.
     * 
     * Validates permissions based on user role and club membership.
     * 
     * @param User $user The user to check
     * @param Club $club The club
     * @param string $action The action to check (e.g., 'edit', 'approve', 'manage_members')
     * @return bool True if user can perform the action
     */
    public function canPerformAction(User $user, Club $club, string $action): bool
    {
        //
    }

    /**
     * Get clubs pending approval.
     * 
     * Returns clubs that have been created but not yet approved.
     * 
     * @param array $filters Optional filters (e.g., created_after, created_by)
     * @return Collection|Club[]
     */
    public function getPendingClubs(array $filters = []): Collection
    {
        //
    }

    /**
     * Get active clubs with member count and event statistics.
     * 
     * Returns clubs with aggregated data for display purposes.
     * 
     * @param array $filters Optional filters (e.g., search, category)
     * @return Collection|Club[]
     */
    public function getActiveClubsWithStats(array $filters = []): Collection
    {
        //
    }

    /**
     * Get clubs that a user can manage.
     * 
     * Returns clubs where user is creator, approver, or has management role.
     * 
     * @param User $user The user
     * @return Collection|Club[]
     */
    public function getManageableClubs(User $user): Collection
    {
        //
    }

    /**
     * Bulk update club statuses.
     * 
     * Updates multiple clubs' statuses in a single transaction.
     * 
     * @param array $clubIds Array of club IDs
     * @param string $status New status to set
     * @param User|null $updatedBy User performing the bulk update
     * @return int Number of clubs updated
     * @throws \Exception If bulk update fails
     */
    public function bulkUpdateStatus(array $clubIds, string $status, ?User $updatedBy = null): int
    {
        //
    }

    /**
     * Get club statistics and analytics.
     * 
     * Returns comprehensive statistics including member count, event count, etc.
     * 
     * @param Club $club The club
     * @return array Statistics array
     */
    public function getClubStatistics(Club $club): array
    {
        //
    }

    /**
     * Validate club data before creation or update.
     * 
     * Performs business rule validation beyond basic Laravel validation.
     * 
     * @param array $data Club data to validate
     * @param Club|null $club Existing club (for updates)
     * @return array ['valid' => bool, 'errors' => array]
     */
    public function validateClubData(array $data, ?Club $club = null): array
    {
        //
    }

    /**
     * Check if a club slug is available.
     * 
     * Validates slug uniqueness, optionally excluding a specific club (for updates).
     * 
     * @param string $slug The slug to check
     * @param Club|null $excludeClub Club to exclude from uniqueness check
     * @return bool True if slug is available
     */
    public function isSlugAvailable(string $slug, ?Club $club = null): bool
    {
        //
    }

    /**
     * Request to join a club.
     * 
     * Creates a pending join request for a user.
     * 
     * @param Club $club The club to join
     * @param User $user The user requesting to join
     * @return ClubJoinRequest The created join request
     * @throws \Exception If user is already a member, has a pending request, or is not a student
     */
    public function requestJoin(Club $club, User $user): ClubJoinRequest
    {
        // Enforce role-based access control: only students can request to join
        if ($user->role !== 'student') {
            throw new \Exception("Only students are allowed to request to join clubs.");
        }

        // Check if user is already a member
        if ($this->hasMember($club, $user)) {
            throw new \Exception("User is already a member of this club.");
        }

        // Check for existing pending request
        $existingRequest = ClubJoinRequest::where('club_id', $club->id)
            ->where('user_id', $user->id)
            ->where('status', 'pending')
            ->first();

        if ($existingRequest) {
            throw new \Exception("A pending join request already exists for this user.");
        }

        return DB::transaction(function () use ($club, $user) {
            return ClubJoinRequest::create([
                'club_id' => $club->id,
                'user_id' => $user->id,
                'status' => 'pending',
            ]);
        });
    }

    /**
     * Approve a join request and add the user as a member.
     * 
     * @param Club $club The club
     * @param User $user The user whose request to approve
     * @param User|null $approver The user approving the request
     * @return bool True if approved successfully
     * @throws \Exception If no pending request exists, user is already a member, or approver is not a club account
     */
    public function approveJoin(Club $club, User $user, ?User $approver = null): bool
    {
        // Enforce role-based access control: only club accounts can approve join requests
        if (!$approver) {
            throw new \Exception("Approver must be provided.");
        }
        if ($approver->role !== 'club') {
            throw new \Exception("Only club accounts are allowed to approve join requests.");
        }

        // Find pending join request
        $request = ClubJoinRequest::where('club_id', $club->id)
            ->where('user_id', $user->id)
            ->where('status', 'pending')
            ->first();

        if (!$request) {
            throw new \Exception("No pending join request found for this user.");
        }

        // Check if user is already a member
        if ($this->hasMember($club, $user)) {
            throw new \Exception("User is already a member of this club.");
        }

        return DB::transaction(function () use ($club, $user, $request, $approver) {
            // Mark request as approved
            $request->status = 'approved';
            $request->save();

            // Add user to club
            $this->addMember($club, $user);

            return true;
        });
    }

    /**
     * Reject a join request.
     * 
     * @param Club $club The club
     * @param User $user The user whose request to reject
     * @param User|null $rejector The user rejecting the request
     * @return bool True if rejected successfully
     * @throws \Exception If no pending request exists or rejector is not a club account
     */
    public function rejectJoin(Club $club, User $user, ?User $rejector = null): bool
    {
        // Enforce role-based access control: only club accounts can reject join requests
        if (!$rejector) {
            throw new \Exception("Rejector must be provided.");
        }
        if ($rejector->role !== 'club') {
            throw new \Exception("Only club accounts are allowed to reject join requests.");
        }

        // Find pending join request
        $request = ClubJoinRequest::where('club_id', $club->id)
            ->where('user_id', $user->id)
            ->where('status', 'pending')
            ->first();

        if (!$request) {
            throw new \Exception("No pending join request found for this user.");
        }

        return DB::transaction(function () use ($request) {
            // Mark request as rejected
            $request->status = 'rejected';
            $request->save();

            return true;
        });
    }

    /**
     * Log an action for audit purposes.
     * 
     * Creates a ClubLog record for internal audit logging.
     * 
     * @param Club $club The club
     * @param string $action The action performed
     * @param User $actor The user who performed the action
     * @param User|null $target Optional target user
     * @param array $meta Optional metadata
     * @return void
     */
    protected function log(Club $club, string $action, User $actor, ?User $target = null, array $meta = []): void
    {
        ClubLog::create([
            'club_id' => $club->id,
            'action' => $action,
            'actor_id' => $actor->id,
            'target_user_id' => $target?->id,
            'metadata' => $meta,
        ]);
    }
}
